-- TODO

CREATE DATABASE IF NOT EXISTS World;
USE World;

DROP TABLE IF EXISTS Country;

START TRANSACTION;

CREATE TABLE Country (
  CountryID INTEGER PRIMARY KEY AUTO_INCREMENT,
  CountryName VARCHAR(255) NOT NULL,
  CountryCode VARCHAR(255) NOT NULL,
  Capital VARCHAR(255) NOT NULL,
  Continent VARCHAR(255) NOT NULL,
--  CONSTRAINT PK_Country PRIMARY KEY (CountryID),
  CONSTRAINT UC_CountryName UNIQUE (CountryName),
  CONSTRAINT UC_CountryCode UNIQUE (CountryCode)
);

INSERT INTO Country (CountryID, CountryName, CountryCode, Capital, Continent) VALUES
(1, 'Afghanistan', 'AF', 'Kabul', 'Asia'),
(2, 'Albania', 'AL', 'Tirana', 'Europe'),
(3, 'Algeria', 'DZ', 'Algiers', 'Africa'),
(4, 'Andorra', 'AD', 'Andorra la Vella', 'Europe'),
(5, 'Angola', 'AO', 'Luanda', 'Africa'),
(6, 'Antigua and Barbuda', 'AG', 'St. John''s', 'North America'),
(7, 'Argentina', 'AR', 'Buenos Aires', 'South America'),
(8, 'Armenia', 'AM', 'Yerevan', 'Asia'),
(9, 'Australia', 'AU', 'Canberra', 'Oceania'),
(10, 'Austria', 'AT', 'Vienna', 'Europe'),
(11, 'Azerbaijan', 'AZ', 'Baku', 'Asia'),
(12, 'Bahamas', 'BS', 'Nassau', 'North America'),
(13, 'Bahrain', 'BH', 'Manama', 'Asia'),
(14, 'Bangladesh', 'BD', 'Dhaka', 'Asia'),
(15, 'Barbados', 'BB', 'Bridgetown', 'North America'),
(16, 'Belarus', 'BY', 'Minsk', 'Europe'),
(17, 'Belgium', 'BE', 'Brussels', 'Europe'),
(18, 'Belize', 'BZ', 'Belmopan', 'North America'),
(19, 'Benin', 'BJ', 'Porto-Novo', 'Africa'),
(20, 'Bhutan', 'BT', 'Thimphu', 'Asia'),
(21, 'Bolivia', 'BO', 'Sucre', 'South America'),
(22, 'Bosnia and Herzegovina', 'BA', 'Sarajevo', 'Europe'),
(23, 'Botswana', 'BW', 'Gaborone', 'Africa'),
(24, 'Brazil', 'BR', 'Brasília', 'South America'),
(25, 'Brunei', 'BN', 'Bandar Seri Begawan', 'Asia'),
(26, 'Bulgaria', 'BG', 'Sofia', 'Europe'),
(27, 'Burkina Faso', 'BF', 'Ouagadougou', 'Africa'),
(28, 'Burundi', 'BI', 'Gitega', 'Africa'),
(29, 'Côte d''Ivoire', 'CI', 'Yamoussoukro', 'Africa'),
(30, 'Cabo Verde', 'CV', 'Praia', 'Africa'),
(31, 'Cambodia', 'KH', 'Phnom Penh', 'Asia'),
(32, 'Cameroon', 'CM', 'Yaoundé', 'Africa'),
(33, 'Canada', 'CA', 'Ottawa', 'North America'),
(34, 'Central African Republic', 'CF', 'Bangui', 'Africa'),
(35, 'Chad', 'TD', 'N''Djamena', 'Africa'),
(36, 'Chile', 'CL', 'Santiago', 'South America'),
(37, 'China', 'CN', 'Beijing', 'Asia'),
(38, 'Colombia', 'CO', 'Bogotá', 'South America'),
(39, 'Comoros', 'KM', 'Moroni', 'Africa'),
(40, 'Congo', 'CG', 'Brazzaville', 'Africa'),
(41, 'Costa Rica', 'CR', 'San José', 'North America'),
(42, 'Croatia', 'HR', 'Zagreb', 'Europe'),
(43, 'Cuba', 'CU', 'Havana', 'North America'),
(44, 'Cyprus', 'CY', 'Nicosia', 'Europe'),
(45, 'Czechia', 'CZ', 'Prague', 'Europe'),
(46, 'Democratic Republic of the Congo', 'CD', 'Kinshasa', 'Africa'),
(47, 'Denmark', 'DK', 'Copenhagen', 'Europe'),
(48, 'Djibouti', 'DJ', 'Djibouti', 'Africa'),
(49, 'Dominica', 'DM', 'Roseau', 'North America'),
(50, 'Dominican Republic', 'DO', 'Santo Domingo', 'North America'),
(51, 'Ecuador', 'EC', 'Quito', 'South America'),
(52, 'Egypt', 'EG', 'Cairo', 'Africa'),
(53, 'El Salvador', 'SV', 'San Salvador', 'North America'),
(54, 'Equatorial Guinea', 'GQ', 'Malabo', 'Africa'),
(55, 'Eritrea', 'ER', 'Asmara', 'Africa'),
(56, 'Estonia', 'EE', 'Tallinn', 'Europe'),
(57, 'Eswatini', 'SZ', 'Mbabane', 'Africa'),
(58, 'Ethiopia', 'ET', 'Addis Ababa', 'Africa'),
(59, 'Fiji', 'FJ', 'Suva', 'Oceania'),
(60, 'Finland', 'FI', 'Helsinki', 'Europe'),
(61, 'France', 'FR', 'Paris', 'Europe'),
(62, 'Gabon', 'GA', 'Libreville', 'Africa'),
(63, 'Gambia', 'GM', 'Banjul', 'Africa'),
(64, 'Georgia', 'GE', 'Tbilisi', 'Asia'),
(65, 'Germany', 'DE', 'Berlin', 'Europe'),
(66, 'Ghana', 'GH', 'Accra', 'Africa'),
(67, 'Greece', 'GR', 'Athens', 'Europe'),
(68, 'Grenada', 'GD', 'St. George''s', 'North America'),
(69, 'Guatemala', 'GT', 'Guatemala City', 'North America'),
(70, 'Guinea', 'GN', 'Conakry', 'Africa'),
(71, 'Guinea-Bissau', 'GW', 'Bissau', 'Africa'),
(72, 'Guyana', 'GY', 'Georgetown', 'South America'),
(73, 'Haiti', 'HT', 'Port-au-Prince', 'North America'),
(74, 'Holy See', 'VA', 'Vatican City', 'Europe'),
(75, 'Honduras', 'HN', 'Tegucigalpa', 'North America'),
(76, 'Hungary', 'HU', 'Budapest', 'Europe'),
(77, 'Iceland', 'IS', 'Reykjavík', 'Europe'),
(78, 'India', 'IN', 'New Delhi', 'Asia'),
(79, 'Indonesia', 'ID', 'Jakarta', 'Asia'),
(80, 'Iran', 'IR', 'Tehran', 'Asia'),
(81, 'Iraq', 'IQ', 'Baghdad', 'Asia'),
(82, 'Ireland', 'IE', 'Dublin', 'Europe'),
(83, 'Israel', 'IL', 'Jerusalem', 'Asia'),
(84, 'Italy', 'IT', 'Rome', 'Europe'),
(85, 'Jamaica', 'JM', 'Kingston', 'North America'),
(86, 'Japan', 'JP', 'Tokyo', 'Asia'),
(87, 'Jordan', 'JO', 'Amman', 'Asia'),
(88, 'Kazakhstan', 'KZ', 'Nur-sultan', 'Asia'),
(89, 'Kenya', 'KE', 'Nairobi', 'Africa'),
(90, 'Kiribati', 'KI', 'Tarawa', 'Oceania'),
(91, 'Kuwait', 'KW', 'Kuwait City', 'Asia'),
(92, 'Kyrgyzstan', 'KG', 'Bishkek', 'Asia'),
(93, 'Laos', 'LA', 'Vientiane', 'Asia'),
(94, 'Latvia', 'LV', 'Riga', 'Europe'),
(95, 'Lebanon', 'LB', 'Beirut', 'Asia'),
(96, 'Lesotho', 'LS', 'Maseru', 'Africa'),
(97, 'Liberia', 'LR', 'Monrovia', 'Africa'),
(98, 'Libya', 'LY', 'Tripoli', 'Africa'),
(99, 'Liechtenstein', 'LI', 'Vaduz', 'Europe'),
(100, 'Lithuania', 'LT', 'Vilnius', 'Europe'),
(101, 'Luxembourg', 'LU', 'Luxembourg', 'Europe'),
(102, 'Madagascar', 'MG', 'Antananarivo', 'Africa'),
(103, 'Malawi', 'MW', 'Lilongwe', 'Africa'),
(104, 'Malaysia', 'MY', 'Kuala Lumpur', 'Asia'),
(105, 'Maldives', 'MV', 'Malé', 'Asia'),
(106, 'Mali', 'ML', 'Bamako', 'Africa'),
(107, 'Malta', 'MT', 'Valletta', 'Europe'),
(108, 'Marshall Islands', 'MH', 'Majuro', 'Oceania'),
(109, 'Mauritania', 'MR', 'Nouakchott', 'Africa'),
(110, 'Mauritius', 'MU', 'Port Louis', 'Africa'),
(111, 'Mexico', 'MX', 'Mexico City', 'North America'),
(112, 'Micronesia', 'FM', 'Palikir', 'Oceania'),
(113, 'Moldova', 'MD', 'Chișinău', 'Europe'),
(114, 'Monaco', 'MC', 'Monaco', 'Europe'),
(115, 'Mongolia', 'MN', 'Ulaanbaatar', 'Asia'),
(116, 'Montenegro', 'ME', 'Podgorica', 'Europe'),
(117, 'Morocco', 'MA', 'Rabat', 'Africa'),
(118, 'Mozambique', 'MZ', 'Maputo', 'Africa'),
(119, 'Myanmar', 'MM', 'Naypyidaw', 'Asia'),
(120, 'Namibia', 'NA', 'Windhoek', 'Africa'),
(121, 'Nauru', 'NR', 'Yaren', 'Oceania'),
(122, 'Nepal', 'NP', 'Kathmandu', 'Asia'),
(123, 'Netherlands', 'NL', 'Amsterdam', 'Europe'),
(124, 'New Zealand', 'NZ', 'Wellington', 'Oceania'),
(125, 'Nicaragua', 'NI', 'Managua', 'North America'),
(126, 'Niger', 'NE', 'Niamey', 'Africa'),
(127, 'Nigeria', 'NG', 'Abuja', 'Africa'),
(128, 'North Korea', 'KP', 'Pyongyang', 'Asia'),
(129, 'North Macedonia', 'MK', 'Skopje', 'Europe'),
(130, 'Norway', 'NO', 'Oslo', 'Europe'),
(131, 'Oman', 'OM', 'Muscat', 'Asia'),
(132, 'Pakistan', 'PK', 'Islamabad', 'Asia'),
(133, 'Palau', 'PW', 'Ngerulmud', 'Oceania'),
(134, 'Palestine State', 'PS', 'Ramallah', 'Asia'),
(135, 'Panama', 'PA', 'Panama City', 'North America'),
(136, 'Papua New Guinea', 'PG', 'Port Moresby', 'Oceania'),
(137, 'Paraguay', 'PY', 'Asunción', 'South America'),
(138, 'Peru', 'PE', 'Lima', 'South America'),
(139, 'Philippines', 'PH', 'Manila', 'Asia'),
(140, 'Poland', 'PL', 'Warsaw', 'Europe'),
(141, 'Portugal', 'PT', 'Lisbon', 'Europe'),
(142, 'Qatar', 'QA', 'Doha', 'Asia'),
(143, 'Romania', 'RO', 'Bucharest', 'Europe'),
(144, 'Russia', 'RU', 'Moscow', 'Europe'),
(145, 'Rwanda', 'RW', 'Kigali', 'Africa'),
(146, 'Saint Kitts and Nevis', 'KN', 'Basseterre', 'North America'),
(147, 'Saint Lucia', 'LC', 'Castries', 'North America'),
(148, 'Saint Vincent and the Grenadines', 'VC', 'Kingstown', 'North America'),
(149, 'Samoa', 'WS', 'Apia', 'Oceania'),
(150, 'San Marino', 'SM', 'San Marino', 'Europe'),
(151, 'São Tomé and Príncipe', 'ST', 'São Tomé', 'Africa'),
(152, 'Saudi Arabia', 'SA', 'Riyadh', 'Asia'),
(153, 'Senegal', 'SN', 'Dakar', 'Africa'),
(154, 'Serbia', 'RS', 'Belgrade', 'Europe'),
(155, 'Seychelles', 'SC', 'Victoria', 'Africa'),
(156, 'Sierra Leone', 'SL', 'Freetown', 'Africa'),
(157, 'Singapore', 'SG', 'Singapore', 'Asia'),
(158, 'Slovakia', 'SK', 'Bratislava', 'Europe'),
(159, 'Slovenia', 'SI', 'Ljubljana', 'Europe'),
(160, 'Solomon Islands', 'SB', 'Honiara', 'Oceania'),
(161, 'Somalia', 'SO', 'Mogadishu', 'Africa'),
(162, 'South Africa', 'ZA', 'Pretoria', 'Africa'),
(163, 'South Korea', 'KR', 'Seoul', 'Asia'),
(164, 'South Sudan', 'SS', 'Juba', 'Africa'),
(165, 'Spain', 'ES', 'Madrid', 'Europe'),
(166, 'Sri Lanka', 'LK', 'Colombo', 'Asia'),
(167, 'Sudan', 'SD', 'Khartoum', 'Africa'),
(168, 'Suriname', 'SR', 'Paramaribo', 'South America'),
(169, 'Sweden', 'SE', 'Stockholm', 'Europe'),
(170, 'Switzerland', 'CH', 'Bern', 'Europe'),
(171, 'Syria', 'SY', 'Damascus', 'Asia'),
(172, 'Tajikistan', 'TJ', 'Dushanbe', 'Asia'),
(173, 'Tanzania', 'TZ', 'Dodoma', 'Africa'),
(174, 'Thailand', 'TH', 'Bangkok', 'Asia'),
(175, 'Timor-Leste', 'TL', 'Dili', 'Asia'),
(176, 'Togo', 'TG', 'Lomé', 'Africa'),
(177, 'Tonga', 'TO', 'Nukuʻalofa', 'Oceania'),
(178, 'Trinidad and Tobago', 'TT', 'Port of Spain', 'North America'),
(179, 'Tunisia', 'TN', 'Tunis', 'Africa'),
(180, 'Turkey', 'TR', 'Ankara', 'Asia'),
(181, 'Turkmenistan', 'TM', 'Ashgabat', 'Asia'),
(182, 'Tuvalu', 'TV', 'Funafuti', 'Oceania'),
(183, 'Uganda', 'UG', 'Kampala', 'Africa'),
(184, 'Ukraine', 'UA', 'Kyiv', 'Europe'),
(185, 'United Arab Emirates', 'AE', 'AKampala', 'Asia'),
(186, 'United Kingdom', 'GB', 'London', 'Europe'),
(187, 'United States of America', 'US', 'Washington, D.C.', 'North America'),
(188, 'Uruguay', 'UY', 'Montevideo', 'South America'),
(189, 'Uzbekistan', 'UZ', 'Tashkent', 'Asia'),
(190, 'Vanuatu', 'VU', 'Port Vila', 'Oceania'),
(191, 'Venezuela', 'VE', 'Caracas', 'South America'),
(192, 'Vietnam', 'VN', 'Hanoi', 'Asia'),
(193, 'Yemen', 'YE', 'Sana''a', 'Asia'),
(194, 'Zambia', 'ZM', 'Lusaka', 'Africa'),
(195, 'Zimbabwe', 'ZW', 'Harare', 'Africa');

COMMIT;